# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 143a6cccaf41dc14df9a728d1457746ed6288ed0f5ed219f3e0387dfbca1ba26a6497cc439a02f2eb0167205ea3e4b37a25baadd9a3d385b620e75369b47c0c9

test:
  secret_key_base: bf924252e55a56037140bba79d3219cb714d572a299785aff30f0bb7870ed09eae5deb1e27bd2145244d93c663e510ea491533d12332b2589fce313a49373573

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
